export const ADD_ITEM_IN_CART = "addItemInCart";
export const SUBTRACT_ITEM_FROM_CART = "subtractItemFromCart";
export const DELETE_ITEM_FROM_CART = "deleteItemFromCart";
export const HANDLE_CLEAR_CART_BTN = "handleClearCartBtn";
export const HANDLE_SEARCH_EVENT = "handleSearchEvent";
export const HANDLE_FILTER_EVENT = "handleFilterHandle";
export const FETCH_PRODUCTS_DATA_REQUEST = " fetchProductsDataRequest";
export const FETCH_PRODUCTS_DATA_SUCCESSFULLY = "fetchProducsDataSuccessfully";
export const FETCH_PRODUCTS_DATA_FAILED = "fetchProductsDataFailed";
